# frozen_string_literal: true

source "https://rubygems.org"

gem "ffi-libfuse", path: "vendor/ffi-libfuse"

group :development, :test do
  gem "minitest", "~> 6.0"
  gem "rake", "~> 13.3"
  gem "webmock", "~> 3.26"
end
